#pragma once

#include <stdint.h>

#define CROPWATCH_LOGO_WIDTH  48U
#define CROPWATCH_LOGO_HEIGHT 48U
#define CROPWATCH_LOGO_BYTES_PER_ROW (CROPWATCH_LOGO_WIDTH / 8U)
#define CROPWATCH_LOGO_SIZE_BYTES (CROPWATCH_LOGO_BYTES_PER_ROW * CROPWATCH_LOGO_HEIGHT)

extern const uint8_t cropwatch_logo_bitmap[CROPWATCH_LOGO_SIZE_BYTES];
