#pragma once

#include <stdint.h>

#define THERMOMETER_ICON_WIDTH  12U
#define THERMOMETER_ICON_HEIGHT 20U
#define THERMOMETER_ICON_BYTES_PER_ROW ((THERMOMETER_ICON_WIDTH + 7U) / 8U)
#define THERMOMETER_ICON_SIZE_BYTES (THERMOMETER_ICON_BYTES_PER_ROW * THERMOMETER_ICON_HEIGHT)

extern const uint8_t thermometer_icon_bitmap[THERMOMETER_ICON_SIZE_BYTES];

